[package]
name = "cipher_pixel_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# Tu motor central
cipher_pixel_lib = { path = "../cipher_pixel_lib" }

# Interfaz y sistema
clap = { version = "4.4", features = ["derive"] }
image = "0.24"

# Seguridad de grado militar
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"

inquire = "0.7.5"
